# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: ip-172-31-87-110
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=JagjeetSidhu1281_DevSecops_Pipeline -Dsonar.organization=JagjeetSidhu1281 -Dsonar.host.url=https://sonarcloud.io -Dsonar.LoginKey=0be3ec830afb92a2cb14c7b174782a0697957a22
